__all__=['', 'RASEAPF_Logon', 'RASEAPF_NonInteractive', 'RASEAPF_Preview']
import typing
from win32helper import win32typing
"""A module encapsulating the Windows 2000 extensions to the Remote Access Service (RAS) API."""

RASEAPF_Logon = ...
RASEAPF_NonInteractive = ...
RASEAPF_Preview = ...