__all__=['RASEAPF_Logon', 'RASEAPF_NonInteractive', 'RASEAPF_Preview']
from typing import *
from .win32typing import *
"""A module encapsulating the Windows 2000 extensions to the Remote Access Service (RAS) API."""

RASEAPF_Logon = ...
RASEAPF_NonInteractive = ...
RASEAPF_Preview = ...